### ISSUE TITLE
Missing permission logs:describeloggroups

### ISSUE THREAD

**Issue by plumdog** [DataDog/cloudformation-template#20]
## Expected Behavior

When using the role created in https://github.com/DataDog/cloudformation-template/blob/master/aws/datadog_integration_role.yaml, expect that all Datadog AWS integrations work report as working from within Datadog.

## Actual Behavior

Amazon Lambda integration reports as "! Broken", and tells me: "Datadog is not authorized to perform action logs:describeloggroups". All other integrations report as working, and based on my investigation are indeed working fine. I'm not sure what functionality is impacted by this missing permission.

And, indeed:
```bash
$ aws iam get-role-policy --role-name DatadogIntegrationRole --policy-name DatadogAWSIntegrationPolicy | jq -r '.PolicyDocument.Statement[0].Action[]' | grep logs
logs:TestMetricFilter
logs:PutSubscriptionFilter
logs:DeleteSubscriptionFilter
logs:DescribeSubscriptionFilters
```

## Steps to Reproduce the Problem

Apply the Cloudformation stack https://github.com/DataDog/cloudformation-template/blob/master/aws/datadog_integration_role.yaml, complete integration with Datadog, review integrations within Datadog.

## Specifications

Unclear. Are they versioned?

**Comment by plumdog** [comment]
Closing, see https://github.com/DataDog/cloudformation-template/pull/21#issuecomment-832703521

**Comment by winjer** [comment]
Hi there,

I've got a !Broken panel for Amazon Lambda showing in my integrations, and it looks to be because of this issue.

![image](https://user-images.githubusercontent.com/166566/134921541-481535b4-7815-40bc-8fbf-2b6246a48c3b.png)

I don't really mind if this permission is not required, but I do mind that I have something on the dashboard showing as Broken when it is not broken.

How do I stop this looking broken?

**Comment by b4stien** [comment]
2.5 years later, I concur: we got a big red warning because of this.
