### ISSUE TITLE
Missing permission logs:describeloggroups caused Lambda panel to show an error

### ISSUE THREAD

**Issue by winjer** [DataDog/cloudformation-template#27]
## Expected Behavior

Amazon Lambda integration panel says it is working

## Actual Behavior

Amazon Lambda integration panel says it is broken

![image](https://user-images.githubusercontent.com/166566/134921820-86e64002-c291-4684-9dcb-43f09f8fa3e1.png)

## Steps to Reproduce the Problem

  1. Just literally have an Amazon Lambda integration

## Specifications

This is related to #20 

The logs:describeloggroups permission is not granted.

this is reported as an error:

![image](https://user-images.githubusercontent.com/166566/134922122-e4c10fe7-bb5e-43f2-a5ef-96c9073a776b.png)

To be clear I am not really bothered about the permission, but I *am* bothered that something is showing broken when it is not.

**Comment by tianchu** [comment]
@winjer this permission is only used by a deprecated feature for submitting custom metrics from Lambda functions https://docs.datadoghq.com/serverless/custom_metrics/#deprecated-cloudwatch-logs. The feature was disabled 2019, but left on for existing customers. Can you DM me your Datadog organization name through our slack community https://chat.datadoghq.com/? I can take a quick look on whether you were using this feature or not, if not, I can disable it for you., which would stop the noise (permission error).

**Comment by tianchu** [comment]
I'm going to close this issue, since most of customers (especially new customers) won't need this permission, and we are not going to make code changes in this repo. But as mentioned previously, people running into this error, can either contact support@datadoghq.com or reach out to me or #serverless channel in our community Slack to disable the feature and get rid of the noise.
